[line_break]
disabled = false

[aws]
disabled = true

[hostname]
ssh_only = true

[git_metrics]
disabled = false

[git_commit]
only_detached = false

[kubernetes]
disabled = true

[[battery.display]]
threshold = 100
style = "green"

[[battery.display]]
threshold = 50
style = "yellow"

[[battery.display]]
threshold = 50
style = "red"

[golang]
symbol = " "
