[line_break]
disabled = false

[aws]
disabled = true

[hostname]
ssh_only = true

[git_metrics]
disabled = false

[git_commit]
only_detached = false

[kubernetes]
disabled = true

[golang]
symbol = " "

[cmd_duration]
show_milliseconds = true
min_time = 0
